### PR TITLE
Add path to CS fundamentals

### PR DESCRIPTION
**Pull request by merimus**

### CODE REVIEW

**Review by Geertiebear — COMMENTED** [review]
This seems like a fine page to add to me, but I'd like to say that this isn't the only way that you can get familiar with CS fundamentals. Another, perfectly valid, way of acquiring required knowledge is to get familiar with a programming language, and explore various data structures and concepts as you go, without following a structured course. (e.g. more of a learn by doing approach). I'd like to avoid coming off as pretentious or gatekeeping on the wiki, since you do not _need_ good knowledge of formal CS fundamentals to be able to get somewhere with osdev, although of course it is useful. I hope it's clear what I mean with this comment.

**Review by lukflug — CHANGES_REQUESTED** [review]
Since a lot of changes to the repository have been made since this PR was submitted, a few changes to the PR are necessary.

Pages have been moved from `modules/ROOT/pages` to `pages`.

In addition, [style guidelines](https://osdev.wiki/pages/guidelines.html) have been instated recently. All commits messages must be adapted to comply with these.

In addition lines longer than 100 columns must be hard wrapped (I'd recommend 80 columns) and new sentences (after a full stop), must start on a new line.

The idea seems fine, however there are formatting issues. The page could be structured differently. In addition, there are problems with tone. The wiki is meant to consist of encyclopedic articles, not instruction manuals.

**Comment by lukflug** [comment]
Shall I squash these commits into a single commit (of course, you will be listed as the author of the commit) and push it to the main branch?

**Comment by merimus** [comment]
yessir

**Pull request closed without merging**
